server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url: http://localhost:${server.port}/eureka/
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
